name:                foundationdb-explorer
version:             0.0.1.0
license:             WTFPL

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- containers
- data-default-class
- deepseq
- errors
- either
- extra
- file-embed
- foundationdb-haskell
- gi-gdk
- gi-glib
- gi-gobject
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- hashable
- ilist
- megaparsec
- pipes
- process
- random
- text
- time
- unordered-containers
- util
- uuid
- vector

library:
  source-dirs: src
  default-extensions:
    - NoImplicitPrelude
  ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

executables:
  foundationdb-explorer:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    dependencies:
    - foundationdb-explorer

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    dependencies:
    - foundationdb-explorer
    - QuickCheck
    - quickcheck-instances
