name:                foundationdb-explorer
version:             0.1.0.0
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- bytestring
- foundationdb-haskell
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- pipes
- process
- sqlite-simple
- text

default-extensions:
- NamedFieldPuns
- OverloadedLabels
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- LambdaCase

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  foundationdb-explorer:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
    - foundationdb-explorer
  data-loader:
    main: Main.hs
    source-dirs: data-loader
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
