name:                foundationdb-explorer
version:             0.1.0.0
license:             BSD3

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- containers
- data-default-class
- errors
- extra
- file-embed
- foundationdb-haskell
- gi-gdk
- gi-glib
- gi-gobject
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- ilist
- megaparsec
- pipes
- process
- text
- time
- uuid
- vector

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  foundationdb-explorer:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
    - foundationdb-explorer

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
    - foundationdb-explorer
    - QuickCheck
    - quickcheck-instances
