FROM fpco/stack-build:lts-14.27

RUN \
  wget https://www.foundationdb.org/downloads/6.2.15/ubuntu/installers/foundationdb-clients_6.2.15-1_amd64.deb && \
  dpkg -i foundationdb-clients_6.2.15-1_amd64.deb
