name: CI

on: [push]

jobs:
  check-formatting:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v3
      
    - uses: mrkkrp/ormolu-action@v9

  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        key: stack
        path: ~/.stack
    
    - uses: actions/cache@v3
      with:
        key: stack-work
        path: .stack-work
    
    - name: 'Install Stack'
      uses: haskell/actions/setup@v2
      with:
        stack-setup-ghc: true
        enable-stack: true

    - run: docker build docker -t foundationdb-explorer:latest
    
    - run: stack test --docker

    - run: |
        sudo apt-get --assume-yes install ruby ruby-dev rubygems build-essential
        sudo gem install fpm
        ./make-deb.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu-package
        path: .make-deb/foundationdb-explorer_*.deb