name: CI

on: [push]

jobs:
  check-formatting:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
      
    - uses: mrkkrp/ormolu-action@v9

  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - uses: mstksg/setup-stack@v2
      env:
        # Workaround https://github.com/mstksg/setup-stack/issues/13
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - run: docker build docker -t foundationdb-explorer:latest
    
    - uses: actions/cache@v1
      with:
        key: stack
        path: ~/.stack
    
    - uses: actions/cache@v1
      with:
        key: stack-work
        path: .stack-work
    
    - run: stack test --docker

    - run: |
        sudo apt-get --assume-yes install ruby ruby-dev rubygems build-essential
        sudo gem install fpm
        ./make-deb.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu-package
        path: .make-deb/foundationdb-explorer_*.deb